<WorkingOptionScreen>:
    GridLayout:
        row: 3
        Label:
            text: 'you have $ saved in your savings, do you want to work?'
            pos: 350, 100
        Button:
            text: 'yes'
            size: 50, 50
            pos: 350, 300
            on_press: root.manager.current = 'ending'
        Button:
            text: 'no'
            size: 50, 50
            pos: 350, 250
            on_press: root.manager.current = 'ending'